package design

const (
	descriptionAlias                           = "Account alias"
	descriptionCreator                         = "Public key of creator's account"
	descriptionSignature                       = "The signature, which can be verified with pubkey"
	descriptionTimestamp                       = "Transaction timestamp"
	descriptionPubkey                          = "Account Public Key"
	descriptionSignatories                     = "Account Signatories"
	descriptionQuorum                          = "最低限必要な数" // TODO
	descriptionMessage                         = "response message"
	descriptionCode                            = "response code"
	descriptionAccount                         = "account"
	descriptionAccounts                        = "accounts"
	descriptionPermissionLedgerAdd             = "ability to create new ledgers"
	descriptionPermissionLedgerRemove          = "ability to remove ledgers"
	descriptionPermissionLedgerName            = "ledger name"
	descriptionPermissionDomainAdd             = "ability to add new domain"
	descriptionPermissionDomainRemove          = "ability to remove existing domain"
	descriptionPermissionPeerRead              = "ability to read peer information"
	descriptionPermissionPeerWrite             = "ability to write(operate) peer"
	descriptionPermissionAccountAdd            = "ability to create new account"
	descriptionPermissionAccountRemove         = "ability to remove account"
	descriptionPermissionAccountGivePermission = "ability to give permissions to account globally"
	descriptionPermissionDomainName            = "domain name"
	descriptionPermissionAssetCreate           = "ability to create asset"
	descriptionPermissionAssetRemove           = "ability to remove asset"
	descriptionPermissionAssetUpdate           = "ability to update asset"
	descriptionPermissionTransfer              = "ability to transfer an asset"
	descriptionPermissionAdd                   = "ability to add some amount to account"
	descriptionPermissionSubtract              = "ability to remove some amount from account"
	descriptionPermissionRead                  = "ability to access some amount from account"
	descriptionPermissionAssetName             = "asset name"
	descriptionSignatory                       = "URL encoded signatory"
	descriptionCurrencyURI                     = "currency's uri" // TODO
	descriptionCurrencyName                    = "currency name"
	descriptionCurrencyDomainName              = "domain name to which currency belongs"
	descriptionCurrencyLedgerName              = "ledger name to which currency belongs"
	descriptionCurrencyDescription             = "currency's description"
	descriptionCurrencyValue                   = "currency's value"
	descriptionCurrencySender                  = "sender's public key"
	descriptionCurrencyReceiver                = "receiver's public key"
	descriptionDomainURI                       = "domain's uri"

	descriptionTransactionSignature = "creator's signature"
	descriptionTransactionCommand   = "transaction's command type"
	descriptionTransactionPublicKey = "ed25519 public key, which should be used to validate the signature"
	descriptionTransactionTimestamp = "transaction creation time"
	descriptionTransactionNonce     = "random 4 bytes"
	descriptionTransactionAction    = "transactions' action"

	descriptionMetaTransaction = ""

	descriptionAccountUUID     = "account's guid"
	descriptionAccountUsername = "account's username"
)
