package design

const (
	descriptionAlias                           = "Account alias"
	descriptionCreator                         = "Public key of creator's account"
	descriptionHash                            = "Transaction hash"
	descriptionSignature                       = "Transaction signature"
	descriptionTimestamp                       = "Transaction timestamp"
	descriptionPubkey                          = "Account Public Key"
	descriptionSignatories                     = "Account Signatories"
	descriptionQuorum                          = "最低限必要な数" // TODO
	descriptionMessage                         = "response message"
	descriptionCode                            = "response code"
	descriptionAccount                         = "account"
	descriptionAccounts                        = "accounts"
	descriptionPermissionLedgerAdd             = "ability to create new ledgers"
	descriptionPermissionLedgerRemove          = "ability to remove ledgers"
	descriptionPermissionLedgerName            = "ledger name"
	descriptionPermissionDomainAdd             = "ability to add new domain"
	descriptionPermissionDomainRemove          = "ability to remove existing domain"
	descriptionPermissionPeerRead              = "ability to read peer information"
	descriptionPermissionPeerWrite             = "ability to write(operate) peer"
	descriptionPermissionAccountAdd            = "ability to create new account"
	descriptionPermissionAccountRemove         = "ability to remove account"
	descriptionPermissionAccountGivePermission = "ability to give permissions to account globally"
	descriptionPermissionDomainName            = "domain name"
	descriptionPermissionAssetCreate           = "ability to create asset"
	descriptionPermissionAssetRemove           = "ability to remove asset"
	descriptionPermissionAssetUpdate           = "ability to update asset"
	descriptionPermissionTransfer              = "ability to transfer an asset"
	descriptionPermissionAdd                   = "ability to add some amount to account"
	descriptionPermissionSubtract              = "ability to remove some amount from account"
	descriptionPermissionRead                  = "ability to access some amount from account"
	descriptionPermissionAssetName             = "asset name"
	descriptionSignatory                       = "URL encoded signatory"
	descriptionAssetURI                        = "asset's uri" // TODO
	descriptionAssetName                       = "asset name"
	descriptionAssetDomainName                 = "domain name to which asset belongs"
	descriptionAssetLedgerName                 = "ledger name to which asset belongs"
	descriptionAssetDescription                = "asset's description"
	descriptionAssetValue                      = "asset's value"
	descriptionAssetSender                     = "sender's public key"
	descriptionAssetReceiver                   = "receiver's public key"
)
