// automatically generated by the FlatBuffers compiler, do not modify

package iroha

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AccountPermissionDomainWrapper struct {
	_tab flatbuffers.Table
}

func GetRootAsAccountPermissionDomainWrapper(buf []byte, offset flatbuffers.UOffsetT) *AccountPermissionDomainWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AccountPermissionDomainWrapper{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AccountPermissionDomainWrapper) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AccountPermissionDomainWrapper) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AccountPermissionDomainWrapper) Permission(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *AccountPermissionDomainWrapper) PermissionLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AccountPermissionDomainWrapper) PermissionBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AccountPermissionDomainWrapperStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AccountPermissionDomainWrapperAddPermission(builder *flatbuffers.Builder, permission flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(permission), 0)
}
func AccountPermissionDomainWrapperStartPermissionVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func AccountPermissionDomainWrapperEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
