// automatically generated by the FlatBuffers compiler, do not modify

package iroha

const (
	AccountPermissionNONE = 0
	AccountPermissionAccountPermissionRoot = 1
	AccountPermissionAccountPermissionLedger = 2
	AccountPermissionAccountPermissionDomain = 3
	AccountPermissionAccountPermissionAsset = 4
)

var EnumNamesAccountPermission = map[int]string{
	AccountPermissionNONE:"NONE",
	AccountPermissionAccountPermissionRoot:"AccountPermissionRoot",
	AccountPermissionAccountPermissionLedger:"AccountPermissionLedger",
	AccountPermissionAccountPermissionDomain:"AccountPermissionDomain",
	AccountPermissionAccountPermissionAsset:"AccountPermissionAsset",
}

