// automatically generated by the FlatBuffers compiler, do not modify

package iroha

const (
	AnyAssetNONE = 0
	AnyAssetComplexAsset = 1
	AnyAssetCurrency = 2
)

var EnumNamesAnyAsset = map[int]string{
	AnyAssetNONE:"NONE",
	AnyAssetComplexAsset:"ComplexAsset",
	AnyAssetCurrency:"Currency",
}

