// automatically generated by the FlatBuffers compiler, do not modify

package iroha

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AssetResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsAssetResponse(buf []byte, offset flatbuffers.UOffsetT) *AssetResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AssetResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AssetResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AssetResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AssetResponse) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AssetResponse) Code() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AssetResponse) MutateCode(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *AssetResponse) Assets(obj *Asset, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AssetResponse) AssetsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AssetResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func AssetResponseAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(message), 0)
}
func AssetResponseAddCode(builder *flatbuffers.Builder, code byte) {
	builder.PrependByteSlot(1, code, 0)
}
func AssetResponseAddAssets(builder *flatbuffers.Builder, assets flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(assets), 0)
}
func AssetResponseStartAssetsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AssetResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
