// automatically generated by the FlatBuffers compiler, do not modify

package iroha

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Asset struct {
	_tab flatbuffers.Table
}

func GetRootAsAsset(buf []byte, offset flatbuffers.UOffsetT) *Asset {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Asset{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Asset) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Asset) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Asset) AssetType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Asset) MutateAssetType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *Asset) Asset(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func AssetStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AssetAddAssetType(builder *flatbuffers.Builder, assetType byte) {
	builder.PrependByteSlot(0, assetType, 0)
}
func AssetAddAsset(builder *flatbuffers.Builder, asset flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(asset), 0)
}
func AssetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
