// automatically generated by the FlatBuffers compiler, do not modify

package iroha

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChaincodeRemove struct {
	_tab flatbuffers.Table
}

func GetRootAsChaincodeRemove(buf []byte, offset flatbuffers.UOffsetT) *ChaincodeRemove {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChaincodeRemove{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ChaincodeRemove) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChaincodeRemove) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChaincodeRemove) CodeName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChaincodeRemove) DomainName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChaincodeRemove) LedgerName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ChaincodeRemoveStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ChaincodeRemoveAddCodeName(builder *flatbuffers.Builder, codeName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(codeName), 0)
}
func ChaincodeRemoveAddDomainName(builder *flatbuffers.Builder, domainName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(domainName), 0)
}
func ChaincodeRemoveAddLedgerName(builder *flatbuffers.Builder, ledgerName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(ledgerName), 0)
}
func ChaincodeRemoveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
