// automatically generated by the FlatBuffers compiler, do not modify

package iroha

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

//////////////////////////////////////////
//////////////////////////////////////////
/// Commands for Chaincode
type ChaincodeAdd struct {
	_tab flatbuffers.Table
}

func GetRootAsChaincodeAdd(buf []byte, offset flatbuffers.UOffsetT) *ChaincodeAdd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChaincodeAdd{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ChaincodeAdd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChaincodeAdd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChaincodeAdd) Code(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ChaincodeAdd) CodeLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ChaincodeAdd) CodeBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ChaincodeAddStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ChaincodeAddAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(code), 0)
}
func ChaincodeAddStartCodeVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ChaincodeAddEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
