// automatically generated by the FlatBuffers compiler, do not modify

package iroha

//////////////////////////////////////////
const (
	CommandNONE = 0
	CommandAdd = 1
	CommandSubtract = 2
	CommandTransfer = 3
	CommandAssetCreate = 4
	CommandAssetRemove = 5
	CommandPeerAdd = 6
	CommandPeerRemove = 7
	CommandPeerSetActive = 8
	CommandPeerSetTrust = 9
	CommandPeerChangeTrust = 10
	CommandAccountAdd = 11
	CommandAccountRemove = 12
	CommandAccountAddSignatory = 13
	CommandAccountRemoveSignatory = 14
	CommandAccountSetUseKeys = 15
	CommandAccountMigrate = 16
	CommandChaincodeAdd = 17
	CommandChaincodeRemove = 18
	CommandChaincodeExecute = 19
	CommandPermissionRemove = 20
	CommandPermissionAdd = 21
)

var EnumNamesCommand = map[int]string{
	CommandNONE:"NONE",
	CommandAdd:"Add",
	CommandSubtract:"Subtract",
	CommandTransfer:"Transfer",
	CommandAssetCreate:"AssetCreate",
	CommandAssetRemove:"AssetRemove",
	CommandPeerAdd:"PeerAdd",
	CommandPeerRemove:"PeerRemove",
	CommandPeerSetActive:"PeerSetActive",
	CommandPeerSetTrust:"PeerSetTrust",
	CommandPeerChangeTrust:"PeerChangeTrust",
	CommandAccountAdd:"AccountAdd",
	CommandAccountRemove:"AccountRemove",
	CommandAccountAddSignatory:"AccountAddSignatory",
	CommandAccountRemoveSignatory:"AccountRemoveSignatory",
	CommandAccountSetUseKeys:"AccountSetUseKeys",
	CommandAccountMigrate:"AccountMigrate",
	CommandChaincodeAdd:"ChaincodeAdd",
	CommandChaincodeRemove:"ChaincodeRemove",
	CommandChaincodeExecute:"ChaincodeExecute",
	CommandPermissionRemove:"PermissionRemove",
	CommandPermissionAdd:"PermissionAdd",
}

