// automatically generated by the FlatBuffers compiler, do not modify

package iroha

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConsensusEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsConsensusEvent(buf []byte, offset flatbuffers.UOffsetT) *ConsensusEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConsensusEvent{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ConsensusEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConsensusEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConsensusEvent) PeerSignatures(obj *Signature, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ConsensusEvent) PeerSignaturesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ConsensusEvent) Transactions(obj *TransactionWrapper, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ConsensusEvent) TransactionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ConsensusEvent) Code() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConsensusEvent) MutateCode(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func ConsensusEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ConsensusEventAddPeerSignatures(builder *flatbuffers.Builder, peerSignatures flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(peerSignatures), 0)
}
func ConsensusEventStartPeerSignaturesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ConsensusEventAddTransactions(builder *flatbuffers.Builder, transactions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(transactions), 0)
}
func ConsensusEventStartTransactionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ConsensusEventAddCode(builder *flatbuffers.Builder, code byte) {
	builder.PrependByteSlot(2, code, 0)
}
func ConsensusEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
