//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: endpoint

package iroha

import "github.com/google/flatbuffers/go"

import (
  context "golang.org/x/net/context"
  grpc "google.golang.org/grpc"
)

// Client API for Hijiri service
type HijiriClient interface{
  Kagami(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* Response, error)  
}

type hijiriClient struct {
  cc *grpc.ClientConn
}

func NewHijiriClient(cc *grpc.ClientConn) HijiriClient {
  return &hijiriClient{cc}
}

func (c *hijiriClient) Kagami(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* Response, error) {
  out := new(Response)
  err := grpc.Invoke(ctx, "/iroha.Hijiri/Kagami", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for Hijiri service
type HijiriServer interface {
  Kagami(context.Context, *Ping) (*flatbuffers.Builder, error)  
}

func RegisterHijiriServer(s *grpc.Server, srv HijiriServer) {
  s.RegisterService(&_Hijiri_serviceDesc, srv)
}

func _Hijiri_Kagami_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(Ping)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(HijiriServer).Kagami(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/iroha.Hijiri/Kagami",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(HijiriServer).Kagami(ctx, req.(* Ping))
  }
  return interceptor(ctx, in, info, handler)
}


var _Hijiri_serviceDesc = grpc.ServiceDesc{
  ServiceName: "iroha.Hijiri",
  HandlerType: (*HijiriServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Kagami",
      Handler: _Hijiri_Kagami_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

