// automatically generated by the FlatBuffers compiler, do not modify

package iroha

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PeerRemove struct {
	_tab flatbuffers.Table
}

func GetRootAsPeerRemove(buf []byte, offset flatbuffers.UOffsetT) *PeerRemove {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PeerRemove{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PeerRemove) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PeerRemove) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PeerRemove) PeerPubKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PeerRemoveStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PeerRemoveAddPeerPubKey(builder *flatbuffers.Builder, peerPubKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(peerPubKey), 0)
}
func PeerRemoveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
