// automatically generated by the FlatBuffers compiler, do not modify

package iroha

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PeerChangeTrust struct {
	_tab flatbuffers.Table
}

func GetRootAsPeerChangeTrust(buf []byte, offset flatbuffers.UOffsetT) *PeerChangeTrust {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PeerChangeTrust{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PeerChangeTrust) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PeerChangeTrust) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PeerChangeTrust) PeerPubKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PeerChangeTrust) Delta() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *PeerChangeTrust) MutateDelta(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func PeerChangeTrustStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PeerChangeTrustAddPeerPubKey(builder *flatbuffers.Builder, peerPubKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(peerPubKey), 0)
}
func PeerChangeTrustAddDelta(builder *flatbuffers.Builder, delta float64) {
	builder.PrependFloat64Slot(1, delta, 0.0)
}
func PeerChangeTrustEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
