// automatically generated by the FlatBuffers compiler, do not modify

package iroha

/////////////////////////////////////
const (
	ProgrammingLanguageJava8 = 0
)

var EnumNamesProgrammingLanguage = map[int]string{
	ProgrammingLanguageJava8:"Java8",
}

