// automatically generated by the FlatBuffers compiler, do not modify

package iroha

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransactionWrapper struct {
	_tab flatbuffers.Table
}

func GetRootAsTransactionWrapper(buf []byte, offset flatbuffers.UOffsetT) *TransactionWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransactionWrapper{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *TransactionWrapper) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransactionWrapper) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransactionWrapper) Tx(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *TransactionWrapper) TxLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TransactionWrapper) TxBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TransactionWrapperStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TransactionWrapperAddTx(builder *flatbuffers.Builder, tx flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(tx), 0)
}
func TransactionWrapperStartTxVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func TransactionWrapperEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
